cachedir: cache
docker:
    fgbio:  docker://diracrnhlbi.azurecr.io/bio/fgbio_env
simg:
    multiqc: https://depot.galaxyproject.org/singularity/multiqc%3A1.16--pyhdfd78af_0
    fastp:   https://depot.galaxyproject.org/singularity/fastp%3A0.23.4--hadf994f_2